\set hugoPwd `echo "$HUGO_PG_PASSWORD"`

CREATE USER hugo WITH PASSWORD :'hugoPwd' IN ROLE api_access;
CREATE SCHEMA AUTHORIZATION hugo;
GRANT USAGE ON SCHEMA kansa TO hugo;
GRANT SELECT, REFERENCES ON ALL TABLES IN SCHEMA kansa TO hugo;
