version: '2'

# docker-compose overlay for production mode
#
# To use, run `make prod` in the project root or directly:
#   docker-compose -f config/docker-compose.base.yaml -f config/docker-compose.prod.yaml up -d
#
# For hints on proper values for environment variables, see docker-compose.dev.yaml.
# This file is stored in the repository as `docker-compose.prod-template.yaml`, which should
# be used as the base of your actual `docker-compose.prod.yaml`.
#
# DO NOT COMMIT PRODUCTION SECRETS TO ANY REPOSITORY

services:
  nginx:
    environment:
      JWT_SECRET:
      SERVER_NAME:
    ports:
      - "80:80"
    restart: always

  hugo:
    environment:
      DATABASE_URL:
      JWT_SECRET:
      SESSION_SECRET:
    restart: always

  kansa:
    environment:
      DATABASE_URL:
      DEBUG: kansa:errors
      JWT_SECRET:
      SESSION_SECRET:
      STRIPE_SECRET_APIKEY:
    restart: always

  raami:
    environment:
      DATABASE_URL:
      SESSION_SECRET:

  kyyhky:
    environment:
      API_URI_ROOT:
      LOGIN_URI_ROOT:
      SENDGRID_APIKEY:
    restart: always

  postgres:
    environment:
      POSTGRES_PASSWORD:
      KANSA_PG_PASSWORD:
      HUGO_PG_PASSWORD:
    restart: always
