version: '2'

# docker-compose overlay for development mode
#
# To use, run `make` in the project root or directly:
#   docker-compose -f config/docker-compose.base.yaml -f config/docker-compose.dev.yaml up -d

services:
  nginx:
    environment:
      JWT_SECRET: dev secret
      SERVER_NAME: localhost
    ports:
      - "4430:80"
    volumes:
      - ../nginx/hugo-packet:/srv/hugo-packet:ro
      - ../nginx/member-files:/srv/member-files:ro
      - ../nginx/ssl:/ssl:ro

  hugo:
    environment:
      CORS_ORIGIN: http://localhost:8080
      DATABASE_URL: postgres://hugo:pwd@postgres:5432/api
      JWT_SECRET: dev secret
      SESSION_SECRET: dev secret

  kansa:
    environment:
      CORS_ORIGIN: http://localhost:8080
      DATABASE_URL: postgres://kansa:pwd@postgres:5432/api
      DEBUG: kansa:*
      JWT_SECRET: dev secret
      SESSION_SECRET: dev secret
      SLACK_ORG: worldcon75
      SLACK_REQ_MEMBER: 'true'
      SLACK_TOKEN:
      STRIPE_SECRET_APIKEY: sk_test_zq022Drx7npYPVEtXAVMaOJT
      STRIPE_SECRET_APIKEY_siteselect: sk_test_35SiP34s6qovtenwPPLguIyY

  raami:
    environment:
      CORS_ORIGIN: http://localhost:8080
      DATABASE_URL: postgres://raami:pwd@postgres:5432/api
      SESSION_SECRET: dev secret

  tarra:
    volumes:
      - ../tarra/fonts:/var/www/html/vendor/tecnickcom/tcpdf/fonts:ro

  tuohi:
    environment:
      VERBOSE_FILL: 'true'

  kyyhky:
    environment:
      API_URI_ROOT: https://localhost:4430/api
      DEBUG: kyyhky:*,sendgrid
      LOGIN_URI_ROOT: https://localhost:4430/#/login
      SENDGRID_APIKEY:

  postgres:
    environment:
      POSTGRES_PASSWORD: adminpwd
      KANSA_PG_PASSWORD: pwd
      HUGO_PG_PASSWORD: pwd
      RAAMI_PG_PASSWORD: pwd
    volumes:
      - ../config/database/dev-people.sql:/docker-entrypoint-initdb.d/90-dev-people.sql:ro
      - ../config/database/fake-people.sql:/docker-entrypoint-initdb.d/91-fake-people.sql:ro
      - ../config/database/hugo-finalists.sql:/docker-entrypoint-initdb.d/90-hugo-finalists.sql:ro
      - ../config/database/payments.sql:/docker-entrypoint-initdb.d/90-payments.sql:ro
